### ISSUE TITLE
Et les mocks alors ?

### ISSUE THREAD

**Issue by Vlequay** [PolytechLyon/4a-isi3-tp3-2016-2017-groupe-2-baud-jeune#1]
Votre couverture de test est pas mal (pas assez fine pour choper les bugs de YetAnotherPerson mais bon  :smirk: ), mais j'aimerais bien que vous me mettiez en place les mocks, c'est vraiment pas long.

Allez jeter un oeil rapidement sur la fin de votre cours sur les tests, vous pigerez rapidement le principe.

Petit détail, vous avez préféré vous servir de `@Parameterized` pour tester toutes les implémentations.
J'ai pas de soucis avec ça, par contre vous avez dû remarquer que c'est pas hyper pratique au niveau du run. Donc deux options : 
1. Vous faites une classe de test par implémentation qui hérite de la classe de test  de base et qui override juste le setup pour instancier la bonne classe (c'est la méthode "propre" que tout la majorité a choisi, et ça vous permet de voir l'annotation `@Suite` vue dans votre cours 😏 ). Mais je comprendrais que vous ayez la flemme donc
2. Vous ajoutez `(name = "{0}")` en argument de l'annotation `@Parameters` et hop 😮 vous y voyez plus clair.

Ça c'était pour le détail. Essayez de m'implémenter les mocks ça serait cool et ça prend pas longtemps 😃 

P.S : si en plus vous me faites la classe abstraite pour les questions d'avant et vous me trouvez des bug dans YetAnotherPerson c'est parfait et ça fera bosser @SamuelJeune 😛. Mais je préfère que vous bossiez le tp4

**Comment by Andzura** [comment]
Les mocks pour les fonctions de OutilsPerson ? ils ont été fait dans les classes TestOutilsPerson & TestOutilsPersonAnonyme. 
Je verrais pour utiliser les Suites, c'est vrai que ça à l'air plus clair pour lire les résultats en suite.

**Comment by Vlequay** [comment]
Wops. En effet, je sais pas ce que j'ai fais, j'ai soit confondu soit mal lu, mea culpa.
Ben parfait alors ;) Je clos, si ya d'autres questions hésite pas.
